remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: MicrobAR Lab
description: Microbiome and Antimicrobial Resistance Laboratory - IBFG
show_downloads: false

nav:
  - name: Home
    link: /
  - name: Team
    link: /team
  - name: Publications
    link: /publications
  - name: Contact
    link: /contact

include:
  - index.md
  - team.md
  - publications.md
  - contact.md

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
